# Numpy Cheatsheet


- **NumPy is a linear algebra library in python.**
- **It is very fast and has bindings to C libraries.**
- **It is used to create arrays in python.**
- **NumPy arrays can be 1-D vectors or multidimensional Matrices**


## 1. numpy.array() method

one dimensional arrays are very easy to create all wew have to do is pass in a list of 1 dimension as an argument to the array() method

In [2]:
# Importing NumPy
import numpy as np

# create a list of your choice
my_list = [1,56,77,34,887,234,674]

# pass the created list to the array() function as an argumrnt and it will create an array out of the given list.
my_arr = np.array(my_list)

my_arr

array([  1,  56,  77,  34, 887, 234, 674])

For creating a 2-D array we have to create a **2-D list** and then we will pass this list as an argument to the array() method.
Similarly, for creating a **n-d array** we have to create a **n-d list** and pass it in as an argument.

In [3]:
# create a 2-d list
D2_list = [[1,3,4,6],
          [5,7,9,11],
          [4,5,7,9]]

# create a 2-d array from the above list
D2_array = np.array(D2_list)

D2_array

array([[ 1,  3,  4,  6],
       [ 5,  7,  9, 11],
       [ 4,  5,  7,  9]])

In [4]:
# create a 3-d list
D3_list = [[[1,3,5],
           [1,4,7],
           [1,5,6]],
           [[1,4,9],
           [1,7,5],
           [2,6,9]]]

# create a 3-d array
D3_array = np.array(D3_list)

D3_array

array([[[1, 3, 5],
        [1, 4, 7],
        [1, 5, 6]],

       [[1, 4, 9],
        [1, 7, 5],
        [2, 6, 9]]])

**If we try to create an array from a list containing mixed datatypes it creates the array most convinient to it**

**Example** - When asked to create an array from a list containing  **int64** and **str** and **boolean** data types. it created an array of **str** type

In [5]:
# list containig int and str and bool
li = [1,4,6,7,'a',9, 'Rohit', True]

# creation of array from the above list
arr_2 = np.array(li)

print('created array = ' + str(arr_2))

# data type of the created array
dtype = arr_2.dtype
print('Data type of created array = ' + str(dtype.name))

created array = ['1' '4' '6' '7' 'a' '9' 'Rohit' 'True']
Data type of created array = str672


## 2. numpy.arange() method

This function is like python's **range()**. It takes three arguments a **start**, a **stop** and a **step**. Then it creates a **One-dimensional** array which contains the numbers belonging to **[start, stop]** set. Here the created array will include the starting number but it will skip away the **stop** number.

The third argument **step** is optional. If we provide step as 2 then the array will skip one number and jump to the second number int the **range(start, stop)**. The value of **step** by default is **1**.

In [6]:
# creating an array using arange()
array = np.arange(1,15)

array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
# creating an array with steps
array = np.arange(1,100,5)

array

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

## 3. numpy.zeros()

This function is used to create an 1-D array or multidimensional Matrices whose all elements are zero.

**For Example** - 
- For creating a zero 1-D array of size n we will use : `np.zeros(n)`
- For creating a zero matrix of size = (m x n) we will pass the tuple **(m , n)** to the method : `np.zeros((m, n))`

In [8]:
# one-dimensional zero-array of size 15
zero_array = np.zeros(15)

zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# zero matrix of size (4*5)
zero_mat = np.zeros((4, 5))

zero_mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 4. numpy.ones()

This function is used to create an 1-D array or multidimensional Matrices whose all elements are **1**.

**For Example** - 
- For creating an 1-D array of ones of size n we will use : `np.ones(n)`
- For creating a matrix of ones of dimensions = (m x n) we will pass the tuple **(m , n)** to the method : `np.ones((m, n))`

In [10]:
# one -dimensional array of ones with size = 15
ones_arr = np.ones(15)

ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# Matrix of ones of size (5*5)
size = (5,5)
ones_mat = np.ones(size)

ones_mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 5. numpy.linspace()

This function takes three arguments - *start*, *stop*, and *number of items*, say n. It then creates an array of n evenly spaced numbers in range *[start, stop]*

**For Example** - `numpy.linspace(2,10,5)` will create a one dimensional array containing 5 evenly spaced numbers from 2 to 10.

In [13]:
# Use of linspace
new_arr = np.linspace(2, 10, 5)

new_arr

array([ 2.,  4.,  6.,  8., 10.])

## 6. numpy.eye()

This function takes in a single integral input and then creates an **identity matrix** of that order.

In [14]:
# Identity matrix of order 4
I = np.eye(4)

I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])